const room = [
  {
    name: "Floor",
    materials: [
      {
        material_name: "Wooden Floor",
        image1:
          "https://cdn.manomano.com/images/images_products/1757077/T/44883519_2.jpg",
        url1: "https://www.manomano.fr/catalogue/p/parquet-massif-bambou-haute-pression-verni-tunder-impression-chene-compatible-pieces-humides-larg-112-cm-121-metre-carre-44308047",
        price1: "29",
        image2:
          "https://cdn.manomano.com/images/images_products/1757077/T/39584386_1.jpg",
        url2: "https://www.manomano.fr/catalogue/p/parquet-massif-chene-baton-rompu-chatillon-naturel-verni-larg-7-cm-054-metre-carre-40341142",
        price2: "53",
        image3:
          "https://cdn.manomano.com/images/images_products/1757077/T/44883519_2.jpg",
        url3: "https://www.manomano.fr/catalogue/p/parquet-massif-bambou-haute-pression-verni-energy-impression-chene-compatible-pieces-humides-larg-112-cm-121-metre-carre-12253677",
        price3: "29",
        image4:
          "https://cdn.manomano.com/images/images_products/1757077/T/46453645_1.jpg",
        url4: "https://www.manomano.fr/catalogue/p/parquet-100-chene-couronne-classique-verni-larg-12-cm-100-metre-carre-45548770",
        price4: "29",
      },
      {
        material_name: "Carpet",
        image1:
          "https://cdn.manomano.com/images/images_products/31911/T/32483674_1.jpg",
        url1: "https://www.manomano.fr/catalogue/p/balsan-along-650-4-m-33855104",
        price1: "30",
        image2:
          "https://cdn.manomano.com/images/images_products/1757077/T/16176942_1.jpg",
        url2: "https://www.manomano.fr/catalogue/p/dalle-moquette-palma-turquoise-impermeable-et-grand-passage-300-metre-carre-15857141",
        price2: "12",
        image3:
          "https://cdn.manomano.com/images/images_products/6664056/T/24060707_1.jpg",
        url3: "https://www.manomano.fr/p/dalle-moquette-acoustique-autoplombante-classe-33-24db-ep-55mm-brun-camel-aa90-2925-boite-20-dalles-50x50cm-5m-tarkett-22609977",
        price3: "19",
        image4: "",
        url4: "",
        price4: "",
      },
      {
        material_name: "Floor tile",
        image1: "",
        url1: "",
        price1: "",
        image2: "",
        url2: "",
        price2: "",
        image3: "",
        url3: "",
        price3: "",
        image4: "",
        url4: "",
        price4: "",
      },
    ],
  },
  {
    name: "Walls",
    materials: [
      {
        material_name: "Paint",
        image1: "",
        url1: "",
        price1: "",
        image2: "",
        url2: "",
        price2: "",
        image3: "",
        url3: "",
        price3: "",
        image4: "",
        url4: "",
        price4: "",
      },
      {
        material_name: "Wallpaper",
        image1: "",
        url1: "",
        price1: "",
        image2: "",
        url2: "",
        price2: "",
        image3: "",
        url3: "",
        price3: "",
        image4: "",
        url4: "",
        price4: "",
      },
    ],
  },
  {
    name: "Heating",
    materials: [
      {
        material_name: "Electric",
        image1: "",
        url1: "",
        price1: "",
        image2: "",
        url2: "",
        price2: "",
        image3: "",
        url3: "",
        price3: "",
        image4: "",
        url4: "",
        price4: "",
      },
      {
        material_name: "Water Radiator",
        image1: "",
        url1: "",
        price1: "",
        image2: "",
        url2: "",
        price2: "",
        image3: "",
        url3: "",
        price3: "",
        image4: "",
        url4: "",
        price4: "",
      },
    ],
  },
];

export default room;
